### ISSUE TITLE
Cann't open the website

### ISSUE THREAD

**Issue by ysc703** [xuefeng7/FACE-LIBRARY#2]
Hi
Thanks for sharing the code.
But I cann't view the image through the browser with the example
 "https://scontent-ort2-1.cdninstagram.com/t51.2885 15/s640x640/sh0.08/e35/17077495_255710568218080_4361264754778439680_n.jpg".

Thanks!

**Comment by xuefeng7** [comment]
I can view the image via browser....

I think if you are in somewhere Instagram is blocked, you can't view the image .... Im sorry.
