### ISSUE TITLE
face datasets

### ISSUE THREAD

**Issue by zhanglaplace** [xuefeng7/FACE-LIBRARY#3]
Hi, can you show me the face image?

the txt file in face_lib only contain the face result .how can i match the result to the face image

**Comment by xuefeng7** [comment]
hi, the way of retrieving the image is showed in the readme....

**Comment by zhanglaplace** [comment]
@xuefeng7 yeah ,i know ,i just want to the relation of the ```python id2code.py 1467331451728886737 (pid)  and the return result uid_pid ```

how can i prepare the pid to generte the image url.

**Comment by xuefeng7** [comment]
I think the answer is listed in the readme ... each face is described as a json item, there is a uid_pid inside
