### ISSUE TITLE
where is the face's position in the label file

### ISSUE THREAD

**Issue by frankieGitHub** [xuefeng7/FACE-LIBRARY#5]
hi, xuefeng:
  thanks for sharing so many face data. But i can't find the face position in according to the origin pictue. Any hint to me will be appericiated.

**Comment by xuefeng7** [comment]
so for each face, we have:

{"timestamp": "1460904440", "resp": [{"attribute": {"gender": {"confidence": 99.984399999999994, "value": "Female"}, "age": {"range": 7, "value": 28}, "race": {"confidence": 68.502099999999999, "value": "White"}, "smiling": {"value": 87.457700000000003}}, "face_id": "b2a535335d5f1dc3ebaec1f021b7ba5f", "tag": "", "position": {"eye_left": {"y": 43.508667000000003, "x": 51.414499999999997}, "center": {"y": 44.666666999999997, "x": 55.666666999999997}, "width": 12.666667, "mouth_left": {"y": 48.637500000000003, "x": 55.328333000000001}, "height": 12.666667, "mouth_right": {"y": 46.140166999999998, "x": 59.346832999999997}, "nose": {"y": 46.653167000000003, "x": 54.822833000000003}, "eye_right": {"y": 40.341999999999999, "x": 56.495832999999998}}}, {"attribute": {"gender": {"confidence": 99.911500000000004, "value": "Female"}, "age": {"range": 5, "value": 17}, "race": {"confidence": 82.457599999999999, "value": "Asian"}, "smiling": {"value": 83.7346}}, "face_id": "81e0663da211ed0f404a89b04dd78ecd", "tag": "", "position": {"eye_left": {"y": 37.719166999999999, "x": 41.079833000000001}, "center": {"y": 41.25, "x": 42.916666999999997}, "width": 11.166667, "mouth_left": {"y": 43.642667000000003, "x": 39.689166999999998}, "height": 11.166667, "mouth_right": {"y": 45.037666999999999, "x": 44.654667000000003}, "nose": {"y": 42.051667000000002, "x": 45.573166999999998}, "eye_right": {"y": 38.983832999999997, "x": 45.886167}}}], "uid_pid": "813540759_1230478088375885881.jpg"}

position: {"eye_left": {"y": 43.508667000000003, "x": 51.414499999999997}, "center": {"y": 44.666666999999997, "x": 55.666666999999997}, 

The first pair of x and y specify the location of the left eye, the second pair specify the center.

**Comment by xuefeng7** [comment]
usually, you want to get the landmarks of interest from the facial image. If you want get an approximation of the face width, maybe you can use the x of the right eye minus the x of the left eye, and crop accordingly.

**Comment by frankieGitHub** [comment]
Thanks for reply, 
I want to crop the face image from the origin picture, i can not do that from the position label.
You may see, the nose position x, or position y always 30.xxxx to 50.xxxx.
Let's say we have 5 faces in one post picture, But all of the 5 faces's nose position range from 30 - 50, this does not make sense. 
I guess the position is for one face cropped image, But not for the origin picture.
Is that true?

Thanks a lot.

**Comment by frankieGitHub** [comment]
@xuefeng7

**Comment by xuefeng7** [comment]
Now I understand you question. If I recall correctly, the positions `(x, y)` are relative. First, you will get the "width" and "height" from the JSON string, for the first face in the above case, "width" and "height" are both 12.666667 and relative. Then, you can use whatever language to get the actual size of the image `(img_x, img_y)` you obtained. Next, you can get the scales by 

`
scale_x = img_x / width; scale_y =  img_y / height. 
`

Let `"center": {"y": 44.666666999999997, "x": 55.666666999999997} ` be the relative position of the face center, then use the scales you can locate the actual position of the center by 

`actual_center_x = relative_center_x * scale_x `
`actual_center_y = relative_center_y * scale_y`

Then, you can crop the face by 

`actual_center_x - width/2, actual_center_y - height/2, width, height`

Hope this will work, let me know.

**Comment by frankieGitHub** [comment]
Hi, Xuefeng:
   i have crop the face finish. There is a import value 100 by 100, and all the position value is according to the 100 by 100.
  In another word, the dataset firstly zoom in the origin picture to 100*100, and get the position from the picture.
  so, scale_x = img_x/100;    scale_y = img_y /100; The others of your describe is correct.

thanks a lot.
@xuefeng7
